// DATA PROTOTYPE FOR FACILITIES
// Facility data for Davao City (sample data for demonstration purposes)
// In a real application, this data would likely come from an API or database

export const FACILITIES = [
  {
    id: 1,
    best: true,
    name: "Southern Philippines Medical Center",
    type: "Government Hospital",
    budget: 800,
    travel: 15,
    wait: 45,
    rating: 4.5,
    tags: ["PhilHealth", "ER"],
    address: "Davao City, Mindanao Ave",
    phone: "(082) 227-0000",
    services: ["Emergency", "General Consultation", "ER Visit", "Pediatrics", "OB-GYN"],
    position: [7.0833, 125.6000],
  },
  {
    id: 2,
    best: false,
    name: "San Pedro Hospital",
    type: "Private Hospital",
    budget: 900,
    travel: 14,
    wait: 40,
    rating: 4.5,
    tags: ["Pediatrics", "OB-GYN"],
    address: "Davao City, San Pedro St",
    phone: "(082) 123-4567",
    services: ["Pediatrics", "OB-GYN", "General Consultation", "Dental"],
    position: [7.0930, 125.6240],
  },
  {
    id: 3,
    best: false,
    name: "Davao Doctors Hospital",
    type: "Private Hospital",
    budget: 1000,
    travel: 13,
    wait: 35,
    rating: 4.5,
    tags: ["Cardiology"],
    address: "Davao City, Cardio Ave",
    phone: "(082) 234-5678",
    services: ["Cardiology", "General Consultation", "Diagnostics", "X-Ray", "ECG"],
    position: [7.1167, 125.6167],
  },
  {
    id: 4,
    best: false,
    name: "Brokenshire Memorial Hospital",
    type: "Mission Hospital",
    budget: 1100,
    travel: 12,
    wait: 30,
    rating: 4.5,
    tags: ["Rehab"],
    address: "Davao City, Rehab Lane",
    phone: "(082) 345-6789",
    services: ["Physical Therapy", "Rehabilitation", "General Consultation", "Speech Therapy"],
    position: [7.0740, 125.5980],
  },
  {
    id: 5,
    best: false,
    name: "Davao Regional Medical Center",
    type: "Government Hospital",
    budget: 600,
    travel: 22,
    wait: 60,
    rating: 4.2,
    tags: ["PhilHealth"],
    address: "Davao City, Regional St",
    phone: "(082) 456-7890",
    services: ["Emergency", "General Consultation", "Diagnostics", "Vaccination"],
    position: [7.0500, 125.5850],
  },
  {
    id: 6,
    best: false,
    name: "Metro Davao Medical Center",
    type: "Private Hospital",
    budget: 1200,
    travel: 10,
    wait: 25,
    rating: 4.7,
    tags: ["Cancer Care"],
    address: "Davao City, Metro Ave",
    phone: "(082) 567-8901",
    services: ["Oncology", "Cancer Care", "General Consultation", "Diagnostics", "MRI Scan", "CT Scan"],
    position: [7.0710, 125.6050],
  },
  {
    id: 7,
    best: false,
    name: "Mindanao Sanitarium Hospital",
    type: "Private Hospital",
    budget: 950,
    travel: 18,
    wait: 50,
    rating: 4.3,
    tags: ["General"],
    address: "Davao City, Sanitarium Rd",
    phone: "(082) 678-9012",
    services: ["General Consultation", "Psychiatry", "Mental Health", "Vaccination"],
    position: [7.0820, 125.5630],
  },
  {
    id: 8,
    best: false,
    name: "Davao Central Clinic",
    type: "Clinic",
    budget: 500,
    travel: 8,
    wait: 20,
    rating: 4.1,
    tags: ["GP", "Checkup"],
    address: "Davao City, Central St",
    phone: "(082) 789-0123",
    services: ["General Consultation", "Check-up", "Vaccination", "Dental Check-up"],
    position: [7.0890, 125.6070],
  },
];
